name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core:
        git:
            url: https://github.com/yegobox/flutterfire.git
            ref: 57e7ddcecc920087bdb4820e212552d26dc1f7fa
            path: packages/firebase_core/firebase_core
  firebase_database: ^10.2.1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
