name: firebase_performance_example
description: Demonstrates how to use the firebase_performance plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_core:
        git:
            url: https://github.com/yegobox/flutterfire.git
            ref: 57e7ddcecc920087bdb4820e212552d26dc1f7fa
            path: packages/firebase_core/firebase_core
  firebase_performance: ^0.9.2+1
  flutter:
    sdk: flutter
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
