name: firebase_ui_oauth
description: Firebase UI widgets for authentication & OAuth
version: 1.4.1
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_oauth

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  desktop_webview_auth: ^0.0.11
  firebase_auth:
    path: ../firebase_auth
  firebase_ui_auth:
    path: ../firebase_ui_auth
  firebase_ui_shared: ^1.3.0
  flutter_svg: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

false_secrets:
  - '/example/**/google-services.json'
  - '/example/**/firebase_options.dart'
  - '/example/**/GoogleService-Info.plist'
  - '/example/lib/config.dart'

flutter:
