name: firebase_core_example
description: Demonstrates how to use the firebase_core plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_core:
        git:
            url: https://github.com/firebase/flutterfire.git
            ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
            path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
