name: firebase_analytics
description:
  Flutter plugin for Google Analytics for Firebase, an app measurement
  solution that provides insight on app usage and user engagement on Android and iOS.
homepage: https://firebase.google.com/docs/analytics
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics
version: 10.4.1

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_analytics_platform_interface: ^3.6.1
  firebase_analytics_web: ^0.5.4+1
  firebase_core:
        git:
            url: https://github.com/yegobox/flutterfire.git
            ref: 57e7ddcecc920087bdb4820e212552d26dc1f7fa
            path: packages/firebase_core/firebase_core
  firebase_core_platform_interface: ^4.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.analytics
        pluginClass: FlutterFirebaseAnalyticsPlugin
      ios:
        pluginClass: FLTFirebaseAnalyticsPlugin
      macos:
        pluginClass: FLTFirebaseAnalyticsPlugin
      web:
        default_package: firebase_analytics_web
