name: firebase_performance_platform_interface
description: A common platform interface for the firebase_performance plugin.
version: 0.1.4+1
homepage: https://firebase.flutter.dev/docs/performance/overview

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.1
  firebase_core:
        git:
            url: https://github.com/firebase/flutterfire.git
            ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
            path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
