name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_core:
        git:
            url: https://github.com/firebase/flutterfire.git
            ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
            path: packages/firebase_core/firebase_core
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  image_picker_for_web: ^2.1.12

flutter:
  uses-material-design: true
  assets:
    - assets/hello.txt
