name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_analytics: ^10.4.1
  firebase_core:
      git:
          url: https://github.com/firebase/flutterfire.git
          ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
          path: packages/firebase_core/firebase_core
  firebase_in_app_messaging: ^0.7.3+1
  firebase_in_app_messaging_platform_interface: ^0.2.4+1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
