name: firebase_ui_auth
description: Pre-built widgets library that are integrated with the variety of the Firebase Auth providers.
version: 1.4.1
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  email_validator: ^2.0.1
  firebase_auth: ^4.6.1
  firebase_core:
        git:
            url: https://github.com/yegobox/flutterfire.git
            ref: 57e7ddcecc920087bdb4820e212552d26dc1f7fa
            path: packages/firebase_core/firebase_core
  firebase_dynamic_links: ^5.3.1
  firebase_ui_localizations: ^1.5.0
  firebase_ui_oauth: ^1.4.1
  firebase_ui_shared: ^1.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0

false_secrets:
  - '/example/**/google-services.json'
  - '/example/**/firebase_options.dart'
  - '/example/**/GoogleService-Info.plist'
  - 'example/lib/config.dart'

flutter:
