name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_auth: ^4.6.1
  firebase_core:
        git:
            url: https://github.com/firebase/flutterfire.git
            ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
            path: packages/firebase_core/firebase_core
  firebase_messaging: ^14.6.1
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0

dev_dependencies:
  http: ^0.13.3

flutter:
  uses-material-design: true
