name: cloud_functions
description: A Flutter plugin allowing you to use Firebase Cloud Functions.
version: 4.3.1
homepage: https://firebase.google.com/docs/functions
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_functions/cloud_functions

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  cloud_functions_platform_interface: ^5.4.1
  cloud_functions_web: ^4.5.1
  firebase_core:
        git:
            url: https://github.com/firebase/flutterfire.git
            ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
            path: packages/firebase_core/firebase_core
  firebase_core_platform_interface: ^4.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.functions
        pluginClass: FlutterFirebaseFunctionsPlugin
      ios:
        pluginClass: FLTFirebaseFunctionsPlugin
      macos:
        pluginClass: FLTFirebaseFunctionsPlugin
      web:
        default_package: cloud_functions_web
