name: firebase_ml_model_downloader_platform_interface
description: A common platform interface for the firebase_ml_model_downloader plugin.
version: 0.1.4+1
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_ml_model_downloader/firebase_ml_model_downloader_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_ml_model_downloader/firebase_ml_model_downloader_platform_interface

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core:
        git:
            url: https://github.com/yegobox/flutterfire.git
            ref: 57e7ddcecc920087bdb4820e212552d26dc1f7fa
            path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
