name: firebase_database
description: Flutter plugin for Firebase Database, a cloud-hosted NoSQL database
  with realtime data syncing across Android and iOS clients, and offline access.
homepage: https://firebase.google.com/docs/database
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_database/firebase_database
version: 10.2.1

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core:
      git:
          url: https://github.com/firebase/flutterfire.git
          ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
          path: packages/firebase_core/firebase_core
  firebase_core_platform_interface: ^4.8.0
  firebase_database_platform_interface: ^0.2.5+1
  firebase_database_web: ^0.2.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.database
        pluginClass: FirebaseDatabasePlugin
      ios:
        pluginClass: FLTFirebaseDatabasePlugin
      macos:
        pluginClass: FLTFirebaseDatabasePlugin
      web:
        default_package: firebase_database_web
