name: firebase_remote_config_example
description: Demonstrates how to use the firebase_remote_config plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core:
        git:
            url: https://github.com/yegobox/flutterfire.git
            ref: 57e7ddcecc920087bdb4820e212552d26dc1f7fa
            path: packages/firebase_core/firebase_core
  firebase_remote_config: ^4.2.1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
