name: cloud_firestore_example
description: Demonstrates how to use the firestore plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  firebase_core:
      git:
          url: https://github.com/firebase/flutterfire.git
          ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
          path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
