name: cloud_firestore_example
description: Demonstrates how to use the firestore plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  firebase_core:
        git:
            url: https://github.com/yegobox/flutterfire.git
            ref: 57e7ddcecc920087bdb4820e212552d26dc1f7fa
            path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
