name: firebase_remote_config_platform_interface
description: A common platform interface for the firebase_remote_config plugin.
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.4.1

environment:
  sdk: '>=2.18.0 <4.0.0'
  # flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.1
  firebase_core:
      git:
          url: https://github.com/firebase/flutterfire.git
          ref: 4897fa02e2963961f24f1ff3a5b8d5e890e919ce
          path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.8.0
